:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - default
  - mailers

:schedule:
  ga_query_job_minute:
    cron: '0 * * * * *'
    class: GaQueryJobMinute

:schedule:
  ga_query_job_daily:
    cron: '0 0 6 * * ?'
    class: GaQueryJobDaily
